# Generated by Django 5.2.8 on 2025-12-10 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagOfGanre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ganre', models.CharField(choices=[('Hardcore', 'Хардкор'), ('RPG', 'РПГ'), ('Adventure', 'Приключение'), ('Technology', 'Технологии'), ('Fantasy', 'Фэнтези'), ('SkyBlock', 'СкайБлок'), ('Vanilla+', 'Ванилла+'), ('PVP', 'ПВП'), ('PVE', 'ПВЕ')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagOfVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition', models.CharField(choices=[('Java Edition', 'Java'), ('Bedrock Edition', 'Bedrock'), ('Java & Bedrock Editions', 'Both')], default='Java Edition', max_length=30)),
                ('version', models.CharField(max_length=10, null=True, verbose_name='Версия игры')),
            ],
        ),
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.RemoveField(
            model_name='articles',
            name='anons',
        ),
        migrations.AddField(
            model_name='articles',
            name='author',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Автор сборки'),
        ),
        migrations.AddField(
            model_name='articles',
            name='short_text',
            field=models.TextField(default='Краткое описание', verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='articles',
            name='status',
            field=models.CharField(choices=[('abandoned', 'Заброшен'), ('active', 'Разрабатывается'), ('unknown', 'Неизвестно')], default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата выхода сборки'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='full_text',
            field=models.TextField(default='Полное описание', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='article_images/')),
                ('alt_text', models.CharField(blank=True, max_length=100)),
                ('image_type', models.CharField(choices=[('logo', 'Логотип'), ('screenshot', 'Скриншот')], default='screenshot', max_length=20)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.articles')),
            ],
        ),
        migrations.AddField(
            model_name='articles',
            name='ganre_tags',
            field=models.ManyToManyField(null=True, to='main.tagofganre'),
        ),
        migrations.AddField(
            model_name='articles',
            name='version_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.tagofversion'),
        ),
    ]
