# Generated by Django 5.2.8 on 2025-12-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tagofganre_tagofversion_alter_articles_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagofversion',
            name='version',
        ),
        migrations.AddField(
            model_name='articles',
            name='version',
            field=models.CharField(max_length=10, null=True, verbose_name='Версия игры'),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выхода сборки'),
        ),
    ]
