# Generated by Django 5.2.8 on 2025-12-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_tagofversion_version_articles_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Проверено модерацией'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='ganre_tags',
            field=models.ManyToManyField(blank=True, to='main.tagofganre'),
        ),
    ]
