# Generated by Django 5.2.10 on 2026-01-27 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_forumcategory_forumtopic_forumpost_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleimage',
            name='alt_text',
        ),
        migrations.RemoveField(
            model_name='articleimage',
            name='image_type',
        ),
        migrations.AddField(
            model_name='articles',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Логотип сборки'),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='main.articles'),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='image',
            field=models.ImageField(upload_to='screenshots/', verbose_name='Скриншот'),
        ),
    ]
